apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hellobhanu
  name: hellobhanu
spec:
  containers:
  - command: ["/bin/sh","-c","ping -i 10 google.com > /tmp/adhoc.txt"]
    image: alpine
    name: hellobhanu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
