apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: hello1bhanu
  name: hello1bhanu
spec:
  containers:
  - command:
    - ping
    - google.com
    image: busybox
    name: hello1bhanu
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
